kind: pipeline
name: default

steps:
  - name: build gcc12
    image: gcc:12
    commands:
      - apt-get update -qq
      - apt-get install -y libusb-1
      - make config.h
      - make
  - name: build gcc11
    image: gcc:11
    commands:
      - apt-get update -qq
      - apt-get install -y libusb-1
      - make config.h
      - make
